// Generated by CoffeeScript 1.6.3
(function() {
  var Circle, circle;

  Circle = (function() {
    function Circle(data) {
      this.target = d3.select("#circles");
      this.svg = this.target.append("svg").attr("height", 400).attr("width", 400);
      this.data = data;
      this.initFunctions();
    }

    Circle.prototype.initFunctions = function() {
      this.drop();
      return this.add();
    };

    Circle.prototype.draw = function() {
      return this.svg.selectAll("circle").data(this.data).enter().append("circle").attr("cx", function(d, i) {
        return (i + 1) * 30;
      }).attr("cy", function(d, i) {
        return (i + 1) * 40;
      }).attr("r", 0).transition().delay(1000).attr("r", function(d) {
        return d * 4;
      });
    };

    Circle.prototype.reDraw = function() {
      this.svg.selectAll("circle").data(this.data).exit().transition().attr("r", 0).remove();
      this.svg.selectAll("circle").data(this.data).enter().append("circle").attr("cx", function(d, i) {
        return (i + 1) * 30;
      }).attr("cy", function(d, i) {
        return (i + 1) * 40;
      }).attr("r", 0).transition().delay(1000).attr("r", function(d) {
        return d * 3;
      });
      return console.log("data:", this.data);
    };

    Circle.prototype.drop = function() {
      var _this = this;
      return $("#drop").click(function() {
        _this.data.pop();
        return _this.reDraw();
      });
    };

    Circle.prototype.add = function() {
      var _this = this;
      return $("#add").click(function() {
        var newCircles;
        newCircles = $("#newData").val().split(",");
        _.map(newCircles, function(circle) {
          return _this.data.push(Number(circle));
        });
        _this.reDraw();
        return console.log(_this.data);
      });
    };

    Circle.prototype.info = function() {
      console.log(this.svg);
      return console.log(this.data);
    };

    return Circle;

  })();

  circle = new Circle([1, 2, 3, 4]);

  circle.info();

  circle.draw();

}).call(this);
