// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("firecharts", ['firebase']);

  app.controller('chartCtrl', function($scope, angularFire, angularFireCollection) {
    var fire, url;
    url = "https://d3questions.firebaseio.com/questions/-J3nC_BtmoIAhlqP5q5I/votes/";
    fire = new Firebase(url);
    $scope.addVote = function() {
      fire.push().set({
        userId: $scope.votecount
      });
      return console.log("vote");
    };
    angularFire(fire, $scope, 'votes', {});
    return $scope.createQuestion = function() {
      url = 'https://d3questions.firebaseio.com/questions/';
      fire = new Firebase(url);
      return fire.push().set({
        title: $scope.question
      });
    };
  });

}).call(this);
