// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("firecharts", ['firebase']);

  app.controller('chartCtrl', function($scope, angularFire, angularFireCollection) {
    var fire, url;
    $scope.votes = [1, 2, 3, 4];
    url = "https://d3questions.firebaseio.com/questions/-J3nC_BtmoIAhlqP5q5I/votes/";
    fire = new Firebase(url);
    angularFire(fire, $scope, 'votes', {}).then(function() {});
    return $scope.showVotes = function() {};
  });

  app.directive('csBar', function() {
    return {
      restrict: "A",
      scope: {
        votes: "="
      },
      template: '<div id="barchart"></div>',
      link: function(scope, element, attrs) {
        var chart, funkyTown, y,
          _this = this;
        element.bind("click", function() {
          return console.log("click this");
        });
        chart = d3.select("#barchart");
        chart.append("svg").attr("width", "400").attr("height", "400");
        y = 0;
        funkyTown = function(data) {
          return console.log("funky", data);
        };
        return scope.$watch('votes', function(n, o) {
          var count;
          if (n) {
            count = _.pluck(n, "count");
            if (_.every(count, _.isNumber()) === true) {
              console.log("n:", count);
              funkyTown(_.pluck(n, "count"));
              chart.selectAll("svg").selectAll("rect").data(_.pluck(n, "count")).enter().append("rect").attr("height", "30px").attr("rx", "5").attr("ry", "5").classed("rect", true).attr("width", function(datum) {
                return datum;
              }).attr("y", function(datum) {
                return y += 30;
              }).attr("x", function(datum) {
                return 0;
              }).attr("fill", "steelblue").attr("stoke", "white");
              console.log("this is the end");
              chart.selectAll("svg").selectAll("text").data(count).enter().append("text").text(function(d) {
                return Math.round(d);
              }).attr("y", function(datum, index) {
                console.log("y", y);
                console.log("index", index);
                return index * 10;
              }).attr("x", function(datum) {
                return Number(datum) + 5;
              });
              return chart.selectAll("svg").selectAll("rect").data(_.pluck(n, "count")).exit().transition().remove();
            }
          }
        });
      }
    };
  });

}).call(this);
