// Generated by CoffeeScript 1.6.3
(function() {
  var Object, quark;

  Object = (function() {
    function Object() {
      this.alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
      this.width = 900;
      this.height = 400;
      this.functions();
    }

    Object.prototype.functions = function() {
      var _this = this;
      this.draw();
      return setInterval((function() {
        return _this.update(_.rest(_.shuffle(_this.alphabet), -5));
      }), 1500);
    };

    Object.prototype.draw = function() {
      return this.svg = d3.select("#alpha").append("svg").attr("width", this.width).attr("height", this.height).append("g").attr("transform", "translate(32," + (this.height / 2) + ")");
    };

    Object.prototype.update = function(data) {
      var _this = this;
      this.text = this.svg.selectAll("text").data(data);
      this.text.attr("class", "update");
      this.text.enter().append("text").attr("class", "enter").attr("x", function(d, i) {
        return i * 32;
      }).attr("dy", ".35em");
      this.text.text(function(d) {
        return d;
      });
      return this.text.exit().remove();
    };

    return Object;

  })();

  quark = new Object;

  quark.alphabet;

  quark.svg;

}).call(this);
